"""Add data models

Revision ID: 546ba9fc507a
Revises: None
Create Date: 2015-01-30 23:06:23.303667

"""

# revision identifiers, used by Alembic.
revision = '546ba9fc507a'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises')),
    sa.UniqueConstraint('name', name=op.f('uq_exercises_name'))
    )
    op.create_table('routines',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_routines')),
    sa.UniqueConstraint('name', name=op.f('uq_routines_name'))
    )
    op.create_table('entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], [u'exercises.id'], name=op.f('fk_entries_exercise_id_exercises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_entries'))
    )
    op.create_table('perscriptions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('sets', sa.Integer(), nullable=False),
    sa.Column('weight', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=False),
    sa.Column('complete_count', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exercise_id'], [u'exercises.id'], name=op.f('fk_perscriptions_exercise_id_exercises')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_perscriptions'))
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('perscriptions')
    op.drop_table('entries')
    op.drop_table('routines')
    op.drop_table('exercises')
    ### end Alembic commands ###
